[project]
name = "reeply"
version = "0.1.0"
description = "Manage your texts. Local-first?"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
  "fastapi>=0.115.8",
  "notion-client>=2.3.0",
  "pydantic>=2.10.6",
  "python-dotenv>=1.0.1",
  "requests>=2.32.3",
  "uvicorn>=0.34.0",
]
